// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} text-brand-ink antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

import "./globals.css";
import type { Metadata } from "next";
import Link from "next/link";
import Sidebar from "@/components/Sidebar";

export const metadata: Metadata = {
  title: "Zetta Dashboard",
  description: "Mini dashboard · Next.js 15 · Tailwind · Framer Motion",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="text-brand-ink antialiased">
        <div className="min-h-dvh grid grid-cols-[auto_1fr]">
          <Sidebar />
          <main className="p-6 md:p-10">
            <header className="mb-6 flex items-center justify-between">
              <h1 className="text-2xl md:text-3xl font-semibold tracking-tight">
                Zetta Dashboard
              </h1>
              <nav className="flex gap-4 text-sm text-brand-dim">
                <Link className="hover:text-brand-ink" href="/">
                  Home
                </Link>
                <Link className="hover:text-brand-ink" href="/posts">
                  Posts
                </Link>
                <Link className="hover:text-brand-ink" href="/users">
                  Users
                </Link>
              </nav>
            </header>

            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
