// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>{children}</body>
//     </html>
//   );
// }

// src/app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import AppShell from "@/components/AppShell";
import SkipLink from "@/components/SkipLink";

export const metadata: Metadata = {
  title: {
    default: "Zetta Dashboard",
    template: "%s | Zetta Dashboard",
  },
  description: "UI-focused mini dashboard built with Next.js 15, Tailwind v4, Framer Motion.",
  robots: "index,follow",
  metadataBase: new URL("https://zetta-dashboard.vercel.app"),
  openGraph: {
    type: "website",
    title: "Zetta Dashboard",
    description: "UI-focused mini dashboard",
    url: "https://zetta-dashboard.vercel.app",
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <SkipLink />
        <AppShell>{children}</AppShell>
      </body>
    </html>
  );
}
